### ISSUE TITLE
Planning new release anytime soon?

### ISSUE THREAD

**Issue by oxoocoffee** [rutura/Qt6QMLBeginnersBookRelease#8]
I just did go through closed issues and based on it, are you planning to make an update at some point?
Cheers,

**Comment by rutura** [comment]
Yes. The book as been officially released here: https://dgakwaya.gumroad.com/l/qt6_qml_for_beginners. But I plan on releasing the free version with the first few chapters in this repo.

**Comment by oxoocoffee** [comment]
Great, I will purchase a copy in a few to support your work :)
I was wondering, what does it mean "547 left" under the Personal option?
Any updates or errata/fixes can be redownloaded after purchase fro the same link?

**Comment by rutura** [comment]
We just published the latest free release of the book. Errata info is not publicly shared at the moment.

**Comment by oxoocoffee** [comment]
@rutura I was not refering to free, but paid version which I like to purchase. Just trying to understand if you will republish updated pdf version including erratas, or you will keep eretas in a seperae document.

**Comment by rutura** [comment]
Now I get it. I haven't organized errata info because the book was still technically under construction. But I can start doing it, now that the book is published. I can set up a csv file somewhere on github and maintain the info there. Any feedback is baked into the latest release of the book, be it free or paid.
